config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :urls, only: [:create, :index]

  root to: 'urls#new'
  get '/:token', to: 'urls#show'
  get '/:token/info', to: 'urls#info'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  before_create :set_token
  validates_presence_of :address
  validates_format_of :address, :with => URI::regexp(%w(http https))

  private

  def set_token
    self.token = generate_token
  end

  def generate_token
    loop do
      token = SecureRandom.alphanumeric(5)
      break token unless Url.find_by(token: token).present?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    @url = Url.create(url_params)
    if @url.valid?
      render :info
    else
      flash.alert = @url.errors.full_messages.join(",")
      render :new
    end
  end

  def index
    @urls = Url.all
  end

  def show
    @url = Url.find_by!(token: params[:token])
    RegisterViewJob.perform_later(@url.token)
    redirect_to @url.address
  end

  def info
    @url = Url.find_by!(token: params[:token])
  end

  private

  def url_params
    params.require(:url).permit(:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiny</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>Urls</h1>

<ul>
<%- @urls.each do |url| %>
   <p> <%= link_to(url.address, controller: 'urls', action: 'info', token: url.token) %> </p>
<%- end %>
</ul>

app/views/urls/info.html.erb
<h1><%= @url.address %></h1>

<h3>Short url: <%= link_to(url_for(controller: 'urls', action: 'show', token: @url.token, only_path: false), controller: 'urls', action: 'show', token: @url.token) %></h3>

<h3>Visits: <%= @url.visits %> </h3>

app/views/urls/new.html.erb
<h1>enter your url</h1>

<h3><%= link_to("All urls", urls_path) %></h3>

<%= form_with model: @url do |form| %>
    <%= form.text_field :address %>
    <%= form.submit %>
<% end %>